name: TenLives
version: '${version}'
main: com.saikonohack.tenlives.TenLives
api-version: '1.20'
load: STARTUP
authors: [saikonohack]
commands:
  gettotem:
    description: Получить Тотем Жизни.
    usage: /gettotem